require 'huginn_agent'

HuginnAgent.load "huginn_delegated_google_calendar_agent/delegated_google_calendar"
HuginnAgent.register 'huginn_delegated_google_calendar_agent/delegated_google_calendar_agent'

